Update to gradle 8
ie3-institute/powerflow pull request #137
Opened 2023-11-10 20:53 UTC by danielfeismann

resolves #136

2023-11-12 09:42 UTC, danielfeismann commented
!test

2024-08-12 16:06 UTC, sebastian-peter requested changes

2024-08-12 16:06 UTC, sebastian-peter commented on build.gradle
> +    "-P:scapegoat:dataDir:" + rootDir + "/build/reports/scapegoat/src/",
One can use this instead to reference the build directory in gradle (same below):

```suggestion
    "-P:scapegoat:dataDir:" + layout.buildDirectory.dir("reports/scapegoat/src/"),
```

2024-08-12 16:06 UTC, sebastian-peter commented on gradle/scripts/mavenCentralPublish.gradle
> +      destination = file("$rootDir/build/generated-pom.xml")
Same as above (if applicable)

2024-08-13 12:53 UTC, sebastian-peter commented on build.gradle
> +    "-P:scapegoat:dataDir:" + rootDir + "/build/reports/scapegoat/src/",
Then nevermind

2024-08-13 12:54 UTC, sebastian-peter approved these changes

2024-08-13 12:54 UTC, merged